### ISSUE TITLE
https://aloisdeniel.github.io/ renders incorrectly

### ISSUE THREAD

**Issue by varon** [aloisdeniel/aloisdeniel.github.io#1]
Your page renders correctly under Http, but not with https.

See https://aloisdeniel.github.io/

**Comment by aloisdeniel** [comment]
Aw,  thanks for pointing me out this issue.

I have to find the right configuration under jekyll.

**Comment by aloisdeniel** [comment]
Okay, switching to `https://` seems to cover the two scenarios.
